#!/usr/bin/env python3
"""Generate native/redlite_native_iq3_tables.h from the pinned llama.cpp ggml-common.h (dev31).

    python3 scripts/dev/gen_iq3_tables.py [.deps/llama.cpp/ggml/src/ggml-common.h]

Copies iq3xxs_grid (256 x u32), iq3s_grid (512 x u32), iq2s_grid (1024 x u64) and kvalues_iq4nl
(16 x i8) verbatim (MIT, see NOTICE.md). The header is committed; this script documents and
reproduces it.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
src = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / ".deps/llama.cpp/ggml/src/ggml-common.h"
text = src.read_text()


def table(name: str) -> list[str]:
    m = re.search(r"GGML_TABLE_BEGIN\((\w+), " + name + r", (\w+)\)(.*?)GGML_TABLE_END", text, re.S)
    if not m:
        raise SystemExit(f"{name} not found in {src}")
    return [v for v in re.findall(r"-?0x[0-9a-fA-F]+|-?\d+", m.group(3))]


out = ["/* Generated by scripts/dev/gen_iq3_tables.py from the pinned llama.cpp ggml/src/ggml-common.h",
       " * (commit in third_party/README.md; MIT, see NOTICE.md). Do not edit. */",
       "#pragma once", "#include <stdint.h>", ""]
for ctype, name, n in (("uint32_t", "iq3xxs_grid", 256), ("uint32_t", "iq3s_grid", 512),
                       ("uint64_t", "iq2s_grid", 1024), ("int8_t", "kvalues_iq4nl", 16)):
    vals = table(name)
    assert len(vals) == n, (name, len(vals))
    out.append(f"static const {ctype} rl_{name}[{n}] = {{")
    for i in range(0, n, 8):
        out.append("    " + ", ".join(vals[i:i + 8]) + ",")
    out.append("};")
    out.append("")
(ROOT / "native/redlite_native_iq3_tables.h").write_text("\n".join(out))
print("wrote native/redlite_native_iq3_tables.h")
