#!/usr/bin/env python3
"""Development-only generator: port the pinned llama.cpp Unicode tables to C.

Reads .deps/llama.cpp/src/unicode-data.cpp (category ranges, whitespace set,
lowercase map) and writes native/redlite_native_unicode_data.h so the native
tokenizer classifies code points exactly like the pinned reference. The data
is derived from the MIT-licensed llama.cpp tables (see NOTICE.md).
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, ".deps", "llama.cpp", "src", "unicode-data.cpp")
DST = os.path.join(ROOT, "native", "redlite_native_unicode_data.h")


def block(text: str, name: str) -> str:
    m = re.search(name + r"[^{]*\{(.*?)\n\};", text, re.S)
    if not m:
        raise SystemExit(f"table {name} not found")
    return m.group(1)


def main() -> int:
    text = open(SRC, encoding="utf-8").read()
    ranges = re.findall(r"\{(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+)\}", block(text, "unicode_ranges_flags"))
    whitespace = re.findall(r"(0x[0-9A-Fa-f]+)", block(text, "unicode_set_whitespace"))
    lowercase = re.findall(r"\{(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+)\}", block(text, "unicode_map_lowercase"))
    pin = "unknown"
    head = os.path.join(ROOT, ".deps", "llama.cpp", ".git", "HEAD")
    try:
        ref = open(head).read().strip()
        pin = ref if not ref.startswith("ref:") else open(os.path.join(ROOT, ".deps", "llama.cpp", ".git", ref[5:])).read().strip()
    except OSError:
        pass
    with open(DST, "w", encoding="utf-8") as out:
        out.write("#pragma once\n")
        out.write("/* Generated by scripts/dev/gen_unicode_data.py from the pinned llama.cpp unicode-data.cpp\n")
        out.write(f" * (commit {pin}). Derived data is MIT licensed; see NOTICE.md. Do not edit by hand. */\n")
        out.write("#include <stdint.h>\n\n")
        out.write("typedef struct { uint32_t start; uint16_t flags; } rl_unicode_range;\n\n")
        out.write(f"#define RL_UNICODE_RANGE_COUNT {len(ranges)}u\n")
        out.write("static const rl_unicode_range rl_unicode_ranges[RL_UNICODE_RANGE_COUNT] = {\n")
        for i, (start, flags) in enumerate(ranges):
            out.write(f"{{{start},{flags}}},")
            if i % 8 == 7:
                out.write("\n")
        out.write("\n};\n\n")
        out.write(f"#define RL_UNICODE_WHITESPACE_COUNT {len(whitespace)}u\n")
        out.write("static const uint32_t rl_unicode_whitespace[RL_UNICODE_WHITESPACE_COUNT] = {\n")
        out.write(",".join(whitespace))
        out.write("\n};\n\n")
        out.write("typedef struct { uint32_t from; uint32_t to; } rl_unicode_pair;\n")
        out.write(f"#define RL_UNICODE_LOWERCASE_COUNT {len(lowercase)}u\n")
        out.write("static const rl_unicode_pair rl_unicode_lowercase[RL_UNICODE_LOWERCASE_COUNT] = {\n")
        for i, (a, b) in enumerate(lowercase):
            out.write(f"{{{a},{b}}},")
            if i % 8 == 7:
                out.write("\n")
        out.write("\n};\n")
    print(f"wrote {DST}: {len(ranges)} ranges, {len(whitespace)} whitespace, {len(lowercase)} lowercase pairs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
